name: "Self-Healing IaC GitHub Action"
description: "Automatically detects, installs, validates, and fixes Infrastructure-as-Code (IaC) configurations using OpenAI GPT."
author: "willdafoe"
branding:
  icon: "activity"
  color: "blue"

inputs:
  openai_api_key:
    description: "OpenAI API key for generating fixes."
    required: true
  github_token:
    description: "GitHub token for creating issues and PRs."
    required: true
  iac_tool:
    description: "Specify the IaC tool (terraform, pulumi, ansible, packer) or use 'auto' to detect automatically."
    required: false
    default: "auto"
  debug_only:
    description: "Run in debug mode without making changes (true/false)."
    required: false
    default: "false"
  enable_rollback:
    description: "Enable rollback if a fix fails (true/false)."
    required: false
    default: "true"
  retry_count:
    description: "Number of retries for OpenAI fix generation."
    required: false
    default: "3"
  auto_merge:
    description: "Automatically merge successful fixes (true/false)."
    required: false
    default: "false"
  auto_deploy:
    description: "Automatically deploy validated configurations (true/false)."
    required: false
    default: "false"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    IAC_TOOL: ${{ inputs.iac_tool }}
    DEBUG_ONLY: ${{ inputs.debug_only }}
    ENABLE_ROLLBACK: ${{ inputs.enable_rollback }}
    RETRY_COUNT: ${{ inputs.retry_count }}
    AUTO_MERGE: ${{ inputs.auto_merge }}
    AUTO_DEPLOY: ${{ inputs.auto_deploy }}
