name: "Self-Healing GitHub Action"
description: "Automatically fixes failing code using ChatGPT."
author: "Your Name"
inputs:
  debug_only:
    description: "Set to true to only comment on PRs. False to auto-fix."
    required: true
    default: "true"
  openai_api_key:
    description: "OpenAI API Key"
    required: true
  github_token:
    description: "GitHub Token for committing and PRs"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
