name: Self-Healing Test

on:
  push:
    branches:
      - main
      - dev

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test_self_healing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Run Self-Healing Action
        uses: willdafoe/openai.gpt.github-action@main
        with:
          debug_only: false
          enable_rollback: true
          retry_count: 3
          auto_merge: true
          iac_tool: "auto"
          openai_api_key: ${{ env.OPENAI_API_KEY }}  # ✅ Ensure this exists
          github_token: ${{ secrets.GITHUB_TOKEN }}      # ✅ Use built-in GitHub token
