name: Self-Healing Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test_self_healing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        iac_tool: [terraform, pulumi, ansible, packer]

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      # ✅ Setup Terraform
      - name: Setup Terraform
        if: matrix.iac_tool == 'terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      # ✅ Setup Pulumi
      - name: Setup Pulumi
        if: matrix.iac_tool == 'pulumi'
        uses: pulumi/actions@v5
        with:
          pulumi-version: latest

      # ✅ Install Ansible (No Official GitHub Action Available)
      - name: Install Ansible
        if: matrix.iac_tool == 'ansible'
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      # ✅ Setup Packer
      - name: Setup Packer
        if: matrix.iac_tool == 'packer'
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: latest

      # ✅ Create Example IaC Files for Testing
      - name: Generate Test Files for ${{ matrix.iac_tool }}
        run: |
          case "${{ matrix.iac_tool }}" in
            terraform)
              echo 'resource "null_resource" "test" {}' > main.tf
              mkdir .terraform
              ;;
            pulumi)
              echo 'name: pulumi-test' > Pulumi.yaml
              echo 'runtime: python' >> Pulumi.yaml
              ;;
            ansible)
              echo '[defaults]' > ansible.cfg
              echo 'inventory = ./inventory' >> ansible.cfg
              echo 'all:\n  hosts:\n    localhost:' > inventory
              echo '- hosts: localhost\n  tasks:\n    - name: Ping\n      ping:' > playbook.yml
              ;;
            packer)
              echo '{ "builders": [{ "type": "null" }] }' > packer.json
              ;;
          esac

      # ✅ Run Self-Healing Action for the Specific IaC Tool
      - name: Run Self-Healing Action for ${{ matrix.iac_tool }}
        uses: willdafoe/openai.gpt.github-action@main
        with:
          debug_only: true
          enable_rollback: false
          retry_count: 1
          auto_merge: false
          iac_tool: "${{ matrix.iac_tool }}"
          openai_api_key: ${{ env.OPENAI_API_KEY }}
          github_token: ${{ env.GITHUB_TOKEN }}
